.dockerignore, Dockerfile, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/StaticContentRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/ConfigurationDependencyInjection.kt
* make frontend available on `/` path
=> Serve static content

backend/build.gradle.kts, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/PatientRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/QuestionRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/Routes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/RoutesSetup.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/ServiceRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/KtorInstallation.kt
closes #19
swagger bezi na `localhost:8080/swagger-ui` cc @misslecter
=> add basic swagger UI

backend/src/main/resources/db/migration/V2__Populate_questions.sql
=> Populate questions table with correct questions

.github/workflows/release.yml
=> Production pipeline

backend/src/main/kotlin/blue/mild/covid/vaxx/error/ExceptionHandling.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/error/ValidationException.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/ValidationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/ConfigurationDependencyInjection.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/DependencyInjection.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/KtorInstallation.kt
Closes [#13](https://github.com/mild-blue/covid-vaxx/issues/13)
=> Validation for form input DTO.

backend/src/main/kotlin/blue/mild/covid/vaxx/service/ValidationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/DependencyInjection.kt
=> Validation of answers added.

backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt
=> PersonalNumber normalization added.

backend/src/main/resources/db/migration/V2__populate_questions.sql
jenom at nepushuju do tve prace
=> db questions typo

backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Answer.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Patient.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Question.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/PatientDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/resources/db/migration/V1__create_first_scheme.sql, backend/src/main/resources/db/migration/V2__populate_questions.sql
=> Metadata of table create/update/delete added.

frontend/src/app/app.component.html, frontend/src/app/app.component.ts, frontend/src/app/app.validators.ts
=> 65 email validation fe

backend/src/main/kotlin/blue/mild/covid/vaxx/auth/JwtService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Answer.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/DatabaseSetup.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/InsuranceCompany.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Patient.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Question.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/BearerTokenDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/HealthDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/InsuranceCompanyDetailsDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/JwtDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/PatientDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/ServiceHealthDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/ServiceRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/UserRoute.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/EntityIdProvider.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/DependencyInjection.kt
* closes #71 
* backend support pro #62
=> Various fixes and refactoring

backend/build.gradle.kts, backend/src/main/kotlin/blue/mild/covid/vaxx/error/ExceptionHandling.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/PatientRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/UserRoute.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/AuthorizedRouteSelector.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/DiModule.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/Exceptions.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/Extensions.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/JwtAuthProvider.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/JwtService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/RoleBasedAuthorization.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/UserPrincipal.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/ratelimiting/Exceptions.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/ratelimiting/LinearRateLimiter.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/ratelimiting/RateLimiting.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/UserService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/KtorInstallation.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/security/ratelimiting/LinearRateLimiterTest.kt
=> Rate limiting

frontend/src/app/components/dialogs/gdpr/gdpr.component.html
=> Gdpr update

frontend/src/app/pages/home/home.component.ts
=> Email validation

frontend/src/app/pages/admin/admin.component.html, frontend/src/app/pages/admin/admin.component.scss, frontend/src/app/pages/admin/admin.component.ts
=> Add logout

frontend/src/app/pages/home/home.component.ts, frontend/src/app/parsers/insurance.parser.ts, frontend/src/app/parsers/patient.parser.ts
=> Insurance company is not working in admin section

backend/src/main/resources/templates/RegistrationConfirmation.ftl
=> Adding images to email temmplate #81

backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/InsuranceCompany.kt, frontend/src/app/generated/model/patientRegistrationDtoIn.ts, frontend/src/app/parsers/to-generated/insurance.parse.ts
viz https://www.finance.cz/pojisteni/seznamy/zdravotni-pojistovny/
=> prejmenovany zdravotni pojistovny, serazeny podle cisla

backend/Makefile, backend/README.md, backend/build.gradle.kts, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/request/MultiplePatientsQueryDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/request/PatientUpdateDtoIn.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/error/ExceptionHandling.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/PatientRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/QuestionRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/ServiceRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/UserRoute.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/Exceptions.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/JwtAuthProvider.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/IsinRegistrationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/MailJetEmailService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/MailService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/MemoryCacheService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PasswordHashProvider.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/QuestionService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/dummy/DummyMailService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/DependencyInjection.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/EnvVariables.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/KtorInstallation.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/platform/LoadTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/platform/PatientRegistrationBuilder.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/platform/PerformanceTest.kt
=> Update libraries and write readme and overall cleanup

backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/ValidationService.kt
=> Fixes out of bound exception during personal number validation

backend/src/main/resources/templates/RegistrationConfirmation.ftl
@misslecter logo uplne nevim jak je mysleno. V Gmailu mi to pred upravou vypada takto
=> uprave html emailove sablony

.github/workflows/pr.yml, backend/build.gradle.kts, backend/detekt.yml, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/Answer.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/DatabaseTypeLength.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/InsuranceCompany.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/Patient.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/Question.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/User.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/repository/PatientRepository.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/error/ExceptionHandling.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/error/ValidationException.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/error/ValidationExceptions.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/PatientRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/JwtService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/ddos/LinearRateLimiter.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/ddos/RateLimiting.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/IsinRegistrationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/ValidationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/ConfigurationDependencyInjection.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/DependencyInjection.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/security/ddos/LinearRateLimiterTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/service/ValidationServiceTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/util/PersonalNumberGenerator.kt
* closes #52 
* closes #60 
* closes #139
* related #140
* related #35
=> Unit tests for validation service

backend/src/main/kotlin/blue/mild/covid/vaxx/setup/KtorInstallation.kt
* tohle umozni mit adresu https://vaccination.mild.blue/admin ktera ukaze admin sekci (v soucasne chvili vraci 404)
=> Static redirects form /admin to /#/admin

frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/pages/home/home.component.ts, frontend/src/app/pages/registration-done/registration-done.component.html, frontend/src/app/pages/registration-done/registration-done.component.scss, frontend/src/app/pages/registration-done/registration-done.component.spec.ts, frontend/src/app/pages/registration-done/registration-done.component.ts, frontend/src/app/services/patient/patient.service.ts
=> Page after successful registration #51

backend/src/main/kotlin/blue/mild/covid/vaxx/dto/config/MailJetConfigurationDto.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/ConfigurationDependencyInjection.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/EnvVariables.kt
=> Wrong subject in email

frontend/src/app/components/dialogs/gdpr/gdpr.component.html, frontend/src/app/pages/admin/edit/admin-edit.component.ts
Administrativni/Administracni nikde nevidím
=> Diakritika

.github/workflows/release.yml
Pokud umi env promenne pri jejich defini v envu subsituovat, dal bych ty jmena do konstant, pokud ne, seru na to.
=> Update of the ECS production deployment.

backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/UserRole.kt
=> Add more roles

frontend/src/app/components/dialogs/no-patient-found/no-patient-found.component.html, frontend/src/app/components/dialogs/success/success-dialog.component.html
Chtel bych u zprav ze pacient byl naockovan a ze byly zmeneny jeho udaje `OK`. Jinde `Zavrit`. Doufam, ze se mi to povedlo...
=> OK vs. Zavřít

frontend/src/app/pipes/body-part-inflected/body-part-inflected.pipe.ts, frontend/src/app/pipes/body-part/body-part.pipe.ts
=> ruka -> paze

frontend/.eslintrc.json, frontend/package-lock.json, frontend/package.json, frontend/src/app/app.module.ts, frontend/src/app/components/form-field/form-field.component.html, frontend/src/app/components/form-field/form-field.component.scss, frontend/src/app/components/form-field/form-field.component.spec.ts, frontend/src/app/components/form-field/form-field.component.ts, frontend/src/app/components/patient-data-item/patient-data-item.component.html, frontend/src/app/components/patient-data-item/patient-data-item.component.scss, frontend/src/app/components/patient-data-item/patient-data-item.component.spec.ts, frontend/src/app/components/patient-data-item/patient-data-item.component.ts, frontend/src/app/components/patient-data/patient-data.component.html, frontend/src/app/components/patient-info-form/patient-info-form.component.html, frontend/src/app/components/patient-info-form/patient-info-form.component.scss, frontend/src/app/components/patient-info-form/patient-info-form.component.ts, frontend/src/app/components/patient-questions-form/patient-questions-form.component.html, frontend/src/app/model/PatientData.ts, frontend/src/app/pages/admin/edit/admin-edit.component.html, frontend/src/app/pages/admin/edit/admin-edit.component.scss, frontend/src/app/pages/admin/edit/admin-edit.component.ts, frontend/src/app/pages/home/home.component.html, frontend/src/app/pages/home/home.component.scss, frontend/src/app/pages/home/home.component.ts, frontend/src/styles/definitions/colors.scss, frontend/src/styles/variables.scss
- Rozšíření kontejneru pro formulář a zvětšení popisků u poliček
- Přidání masky do poliček s rodným číslem a PSČ (telefon má vlastní masku přes plugin, který používáme)
- Validace inputu během psání včetně zobrazení chybové hlášky
- Hláška pod formulářem vysvětlující, jaké informace chybí pro pokračování na další krok
Upravila bych potom zvlášť barvy a fonty, at používáme naše.
Closes #128
=> Better explanation of required format

backend/src/main/kotlin/blue/mild/covid/vaxx/dao/repository/VaccinationSlotRepository.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/PatientRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/VaccinationSlotService.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/LocationRoutesTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/VaccinationSlotRoutesTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/utils/TestBase.kt
* serializace transakci nefungovala tak, jak by mela
* takze sto uzivatelu bookujicich najednou si sebere svoje sloty coz je teda mega pruser
* poor man's solution s mutexem
=> Fix slots booking

backend/src/main/resources/templates/RegistrationConfirmation.ftl, frontend/src/app/pages/registration-done/registration-done.component.html
@misslecter  muzes to prosim dodelat :)
Emaily tam dat jako mailto odkaz
Na stranku s potvrzenim pridat info, ze jim to same bylo odeslano i emailem a at pro jistotu zkontroluji i slozku Spam a Hromadne.
Diky
=> text updates

frontend/src/app/components/patient-data/patient-data.component.html, frontend/src/app/components/patient-questions-form/patient-questions-form.component.html, frontend/src/app/components/progress-loading/progress-loading.component.scss, frontend/src/app/pages/home/home.component.html, frontend/src/app/pages/home/home.component.ts, frontend/src/styles/vendor/mat-snack-bar.scss
Disablujem tlacitko, ukazeme nahore loading bar.
Closes #249
=> Duplicate registration

frontend/src/app/services/alert/alert.service.ts
Ukazujeme po dobu 4s a pak to automaticky zmizi. Taky to muze zavrit driv krizkem.
Closes #247
=> Fade out error messages

backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/DatabaseTypeLength.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/Patients.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/repository/PatientRepository.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/PatientRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/IsinValidationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/PatientService.kt, backend/src/main/resources/db/migration/V6__patient_isin_id.sql, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/VaccinationSlotRoutesTest.kt
Do db ukládám číslo pacienta z isinu. Také jsem vylepšil logování. Pro už validované pacienty uložím místo čísla "validated".
Closes https://github.com/mild-blue/covid-vaxx/issues/242
=> Save isin number

backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/VaccinationSlotDtoOut.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/dto/response/VaccinationSlotDtoOutTest.kt
=> round from time too

frontend/src/app/interceptors/error/error.interceptor.ts
=> Report server error

frontend/src/app/pages/info/info.component.html, frontend/src/app/pages/info/info.component.scss, frontend/src/app/pages/registration-done/registration-done.component.html
Closes https://github.com/mild-blue/covid-vaxx/issues/285
=> Add technical info

backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/UserLogins.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/model/Vaccinations.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/repository/UserRepository.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dao/repository/VaccinationRepository.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/internal/StoreVaccinationRequestDto.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/request/LoginDtoIn.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/response/VaccinationDetailDtoOut.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/JwtService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/security/auth/UserPrincipal.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/UserService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/VaccinationService.kt, backend/src/main/resources/db/migration/V9__vaccine_expiration.sql, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/NurseRoutesTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/UserRoutesTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/VaccinationRouteTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/utils/TestBase.kt, frontend/src/app/generated/model/createVaccinationSlotsDtoIn.ts, frontend/src/app/generated/model/loginDtoIn.ts, frontend/src/app/generated/model/vaccinationDetailDtoOut.ts, frontend/src/app/pages/login/login.component.html, frontend/src/app/pages/login/login.component.scss, frontend/src/app/pages/login/login.component.ts, frontend/src/app/services/auth/auth.service.ts
Otestoval jsem na FE celý workflow a ověřil že datum expirace je zapsaný v obou db tabulkách.
=> Vaccine expiration BE + FE

backend/src/main/kotlin/blue/mild/covid/vaxx/dto/config/IsinConfigurationDto.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/internal/IsinSubjectDto.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/internal/IsinVaccinationCreateOrUpdateDtoIn.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/internal/IsinVaccinationDoseCreateOrUpdateDtoIn.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/internal/IsinVaccinationDoseDto.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/dto/internal/IsinVaccinationDto.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/VaccinationRoutes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/IsinService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/IsinServiceInterface.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/VaccinationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/dummy/DummyIsinService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/ConfigurationDependencyInjection.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/DependencyInjection.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/EnvVariables.kt
And fix url parameters encoding bug
Closes https://github.com/mild-blue/covid-vaxx/issues/217
=> Export vaccination to ISIN

backend/src/main/kotlin/blue/mild/covid/vaxx/routes/Routes.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/routes/ServiceRoutes.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/requests/http-client.env.json, backend/src/test/kotlin/blue/mild/covid/vaxx/requests/test-staging.http, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/ServiceRoutesTest.kt
=> Show statistics publicly.

backend/src/main/kotlin/blue/mild/covid/vaxx/dao/repository/VaccinationSlotRepository.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/service/VaccinationSlotService.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/routes/PatientRoutesTest.kt
* closes #267
* based on the - https://spin.atomicobject.com/2021/02/04/redis-postgresql/
* now the booking is "atomic" in the database and all locking is done by the DB
#unlimited scalling
=> Implement better booking algorithm

backend/src/main/kotlin/blue/mild/covid/vaxx/jobs/EmailRetryJob.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/jobs/Job.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/jobs/JobsRegistrationService.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/jobs/PeriodicExecutorLoop.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/jobs/PeriodicJob.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/jobs/PeriodicJobsDI.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/monitoring/JsonLoggingLayout.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/EnvVariables.kt, backend/src/main/kotlin/blue/mild/covid/vaxx/setup/KtorInstallation.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/jobs/EmailRetryJobTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/jobs/JobsRegistrationServiceTest.kt, backend/src/test/kotlin/blue/mild/covid/vaxx/utils/TestBase.kt
* resend email to people that didn't get it
=> Email retry if failed

backend/src/test/kotlin/blue/mild/covid/vaxx/routes/PatientRoutesTest.kt
No severe issues while implementing the test.
=> test 262 done

backend/src/test/kotlin/blue/mild/covid/vaxx/requests/http-client.env.json, backend/src/test/kotlin/blue/mild/covid/vaxx/requests/test-staging.http, frontend/src/app/app.component.ts, frontend/src/app/generated/api/default.service.ts, frontend/src/app/model/Statistics.ts, frontend/src/app/pages/info/info.component.html, frontend/src/app/pages/info/info.component.ts, frontend/src/app/parsers/statistics.parser.ts, frontend/src/app/services/statistics/statistics.service.spec.ts, frontend/src/app/services/statistics/statistics.service.ts
Closes https://github.com/mild-blue/covid-vaxx/issues/297
=> Show slots number

frontend/src/app/components/dialogs/confirm-patient-data/confirm-patient-data.component.html, frontend/src/app/components/dialogs/confirm-patient-data/confirm-patient-data.component.ts, frontend/src/app/components/dialogs/confirm-vaccination/confirm-vaccination.component.html, frontend/src/app/components/dialogs/confirm-vaccination/confirm-vaccination.component.ts, frontend/src/app/pages/admin/edit/admin-edit.component.html, frontend/src/app/pages/admin/edit/admin-edit.component.ts, frontend/src/app/pages/admin/patient/admin-patient.component.html, frontend/src/app/pages/admin/patient/admin-patient.component.ts
=> Fix 2x vaccinate

backend/src/test/kotlin/blue/mild/covid/vaxx/routes/LocationRoutesTest.kt
`get existing location from the database test` implemented
=> LocationRoutesTest#256

backend/src/test/kotlin/blue/mild/covid/vaxx/routes/VaccinationRouteTest.kt
VaccinationRouteTest #259 implemented
=> Implement VaccinationRouteTest#259

backend/src/test/kotlin/blue/mild/covid/vaxx/routes/VaccinationRouteTest.kt, frontend/src/app/components/dialogs/success/success-dialog.component.html, frontend/src/app/components/dialogs/success/success-dialog.component.ts
Zobrazujeme po potvrzení correctness, po 1. a 2. vakcinaci a po updatu údajů pacienta
Closes https://github.com/mild-blue/covid-vaxx/issues/344
=> Add search again button to success dialog

frontend/src/app/pages/info/info.component.html
=> Modify landing page

frontend/src/app/pages/info/info.component.html
Reverts mild-blue/covid-vaxx#353
=> Enable registration once again

frontend/src/app/components/patient-data/patient-data.component.html
Jako nevim... Asi to bude fungovat, na druhou stranu to zrusi ten warning i ve chvili, kdy si to prohlíží doktor - a tam to mít chceme. To už ale udělat neumím :)
=> Hotfix no first dosage
